### ISSUE TITLE
Crash On Launch

### ISSUE THREAD

**Issue by Sweek9** [JamCoreModding/reaping#2]
As the only mod in the folder it crashed on launch and I saw in the log that it has a required dependency (Architectury) that is not mentioned anywhere on the mods page on Curse Forge. However even with that library, it still crashes on launch. The only difference in the second log file is the missing dependency error on lines 14 and 15. 
Minecraft: 1.20.2
Forge: 48.0.35
Reaping: 3.0.0
Architectury: 10.0.8
Log: 
```
[08Nov2023 21:53:46.341] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Sweek, --version, 1.20.2-forge-48.0.35, --gameDir, /Users/moorgan/Library/Application Support/minecraft, --assetsDir, /Users/moorgan/Library/Application Support/minecraft/assets, --assetIndex, 8, --uuid, ba9a8e5647e542069df6302b8cf8435c, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, , --xuid, , --userType, mojang, --versionType, release, --width, 1920, --height, 1080, --launchTarget, forge_client, --fml.forgeVersion, 48.0.35, --fml.mcVersion, 1.20.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230921.100330]
[08Nov2023 21:53:46.343] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: JVM identified as Microsoft OpenJDK 64-Bit Server VM 17.0.8+7-LTS
[08Nov2023 21:53:46.344] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.1.1 starting: java version 17.0.8 by Microsoft; OS Mac OS X arch aarch64 version 14.1
[08Nov2023 21:53:46.407] [main/INFO] [net.minecraftforge.fml.loading.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow
[08Nov2023 21:53:46.601] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.1
[08Nov2023 21:53:46.614] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.1 got version 4.1
[08Nov2023 21:53:46.740] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/Users/moorgan/Library/Application%20Support/minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2391!/ Service=ModLauncher Env=CLIENT
[08Nov2023 21:53:46.758] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: Apple M1 Ultra GL version 4.1 Metal - 88, Apple
[08Nov2023 21:53:46.893] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /Users/moorgan/Library/Application Support/minecraft/libraries/net/minecraftforge/fmlcore/1.20.2-48.0.35/fmlcore-1.20.2-48.0.35.jar is missing mods.toml file
[08Nov2023 21:53:46.894] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /Users/moorgan/Library/Application Support/minecraft/libraries/net/minecraftforge/javafmllanguage/1.20.2-48.0.35/javafmllanguage-1.20.2-48.0.35.jar is missing mods.toml file
[08Nov2023 21:53:46.894] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /Users/moorgan/Library/Application Support/minecraft/libraries/net/minecraftforge/lowcodelanguage/1.20.2-48.0.35/lowcodelanguage-1.20.2-48.0.35.jar is missing mods.toml file
[08Nov2023 21:53:46.895] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /Users/moorgan/Library/Application Support/minecraft/libraries/net/minecraftforge/mclanguage/1.20.2-48.0.35/mclanguage-1.20.2-48.0.35.jar is missing mods.toml file
[08Nov2023 21:53:46.927] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
[08Nov2023 21:53:46.959] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'architectury', Requested by: 'reaping', Expected range: '[9.1.12,)', Actual version: '[MISSING]'
[08Nov2023 21:53:47.461] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[08Nov2023 21:53:47.463] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forge_client' with arguments [--version, 1.20.2-forge-48.0.35, --gameDir, /Users/moorgan/Library/Application Support/minecraft, --assetsDir, /Users/moorgan/Library/Application Support/minecraft/assets, --uuid, ba9a8e5647e542069df6302b8cf8435c, --username, Sweek, --assetIndex, 8, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, , --xuid, , --userType, mojang, --versionType, release, --width, 1920, --height, 1080]
[08Nov2023 21:53:48.710] [pool-4-thread-1/FATAL] [mixin/]: Mixin apply failed reaping.mixins.json:LivingEntityMixin -> net.minecraft.world.entity.LivingEntity: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on reaping$updateScaleOnEffectRemoved could not find any targets matching 'onEffectRemoved' in net.minecraft.world.entity.LivingEntity. No refMap loaded. [PREINJECT Applicator Phase -> reaping.mixins.json:LivingEntityMixin -> Prepare Injections ->  -> handler$zza000$reaping$updateScaleOnEffectRemoved(Lnet/minecraft/world/effect/MobEffectInstance;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on reaping$updateScaleOnEffectRemoved could not find any targets matching 'onEffectRemoved' in net.minecraft.world.entity.LivingEntity. No refMap loaded. [PREINJECT Applicator Phase -> reaping.mixins.json:LivingEntityMixin -> Prepare Injections ->  -> handler$zza000$reaping$updateScaleOnEffectRemoved(Lnet/minecraft/world/effect/MobEffectInstance;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:142) ~[modlauncher-10.1.1.jar:10.1.1]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:75) ~[modlauncher-10.1.1.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:107) ~[modlauncher-10.1.1.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:37) ~[modlauncher-10.1.1.jar:?]
	at net.minecraftforge.securemodules.SecureModuleClassLoader.readerToClass(SecureModuleClassLoader.java:418) ~[securemodules-2.2.3.jar:?]
	at net.minecraftforge.securemodules.SecureModuleClassLoader.findClass(SecureModuleClassLoader.java:367) ~[securemodules-2.2.3.jar:?]
	at net.minecraftforge.securemodules.SecureModuleClassLoader.loadClass(SecureModuleClassLoader.java:383) ~[securemodules-2.2.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.minecraftforge.registries.GameData.init(GameData.java:108) ~[forge-1.20.2-48.0.35-universal.jar%23152!/:?]
	at net.minecraftforge.registries.GameData.<clinit>(GameData.java:92) ~[forge-1.20.2-48.0.35-universal.jar%23152!/:?]
	at net.minecraft.core.registries.BuiltInRegistries.forge(BuiltInRegistries.java:433) ~[client-1.20.2-20230921.100330-srg.jar%23147!/:?]
	at net.minecraft.core.registries.BuiltInRegistries.forge(BuiltInRegistries.java:413) ~[client-1.20.2-20230921.100330-srg.jar%23147!/:?]
	at net.minecraft.core.registries.BuiltInRegistries.<clinit>(BuiltInRegistries.java:121) ~[client-1.20.2-20230921.100330-srg.jar%23147!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:43) ~[client-1.20.2-20230921.100330-srg.jar%23147!/:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:154) ~[client-1.20.2-20230921.100330-srg.jar%23147!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Jamalam360** [comment]
You need architectury and jam lib, and optionally pehkui (if it's been updated yet). This is in fact mentioned, it's attached to every file in the dependencies section on Modrinth on curseforge
